language: objective-c
os: osx
osx_image: xcode10.2

script:
    - cd Plastic && xcodebuild -scheme 'iOS Framework' -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.2,name=iPhone Xs' clean build test
